### ISSUE TITLE
How to compile ?

### ISSUE THREAD

**Issue by AlexandreFournier** [francisseco/Janus-CUDA-Nbody#1]
There is no Makefile. The README does not say how to compile.

**Comment by francisseco** [comment]
The README says:
To use the modified code install CUDA samples first and make sure you can compile and execute CUDA samples. Navigate to the 5-Simulations/nbody folder and replace the sample files with the provided files.

If you don't know how to install and compile NVIDIA CUDA sample, I suggest you take a look at NVIDIA guides an how-to.
